
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 26 10:53:22 PST 2014
//----------------------------------------------------

package traductor;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SUSTANTIVO = 3;
  public static final int LITERAL = 10;
  public static final int NOMBRE_PROPIO = 7;
  public static final int PRONOMBRE = 9;
  public static final int PALABRA_RESERVADA = 8;
  public static final int ADJETIVO = 4;
  public static final int EOF = 0;
  public static final int SIGNO_PUNTUACION = 11;
  public static final int OTRO = 13;
  public static final int error = 1;
  public static final int ERROR_LEXICO = 12;
  public static final int PREPOSICION = 6;
  public static final int ADVERBIO = 5;
  public static final int VERBO = 2;
}

